### ISSUE TITLE
Lexicographic completeness of shards

### ISSUE THREAD

**Issue by fehlmach** [britram/rains-prototype#20]
Page 5, Shard: " A group of assertions common to a zone, with common signatures, which may be lexicographically complete..."
Page 20: "Shards are lexicographically complete within the range described in its the shard-range value"

According to the draft it is not clear, if shards MUST be lexicographically complete.
Adv: They can be used as a proof of non-existence
Disadv: It restricts the protocol. There might be cases where it makes sense to group some assertions together in a shard instead sending all assertions separately. E.g. it makes sure that either all or none of the assertions are received.

Mitigation: If we do not want to restrict ourselves and have non-existence proofs, we could add a flag to the shard which indicates that it is lexicographic complete.

**Comment by britram** [comment]
Shards MUST be lexicographically sorted; this is old text that needs to be fixed.
