### ISSUE TITLE
lexicographic sorting of shards and assertions

### ISSUE THREAD

**Issue by fehlmach** [britram/rains-prototype#24]
Sec 5.6: "Shards and Assertions in the content array SHOULD be sorted by shard range or name in ascending lexicographic order."

I would make it explicit how it is sorted because for me it is not clear. Is it this way?
assertions are sorted before shards. 
assertions are sorted lexicographically ascending by subject-name
shards are sorted lexicographically ascending firstly by range begin and secondly by range end?

**Comment by britram** [comment]
This is actually a MUST, since you need to sign an object in canonical order.
