### ISSUE TITLE
Representation of delegation object in an assertion

### ISSUE THREAD

**Issue by fehlmach** [britram/rains-prototype#3]
Right now a delegation Object is represented as a N-element array.
From an implementation perspective it would be better to have a 3 element array instead where the first 2 elements are the same but the third element is a cbor array containing the elements of the public key. So we can decouple the parsing of the delegation object form the parsing of the public key data.
We then also do not have to define concatenation of different values of a public key (such as x and y in ECDSA or in any other future algorithm.

**Comment by britram** [comment]
The main reason this is as it is is that pretty much all ciphers define a standard byte array serialization for keys and signatures. For interoperability among implementations and libraries, it's simpler to use this standard serialization than it is to define a new one and require transcoding.
