### ISSUE TITLE
Add sorting definition of object value for each type

### ISSUE THREAD

**Issue by fehlmach** [britram/rains-prototype#36]
Assertions must be sorted deterministically for signature validation in shards. So far the draft only sorts assertions by their name, But there might be assertions for different types and even several assertions per type. We have to define an order on the types (I suggest their code number) and for each type how the objects of this type are sorted.

**Comment by fehlmach** [comment]
That would mean, we encode an object in cbor and then compare the resulting cbor byte strings, right? So we must make sure, that it is clear for each object, how to serialize it in cbor. Which is the case, I think.

**Comment by britram** [comment]
Yep. We need to do this for signing anyway, so we might as well do it for sorting too.
