### ISSUE TITLE
Keyphase

### ISSUE THREAD

**Issue by fehlmach** [britram/rains-prototype#7]
Add an integer to a delegation object and also to the signature meta data to specify the key phase of the public key.

**Comment by fehlmach** [comment]
Currently a server issuing a query for a public key cannot specify which key phase and signature algorithm he requires. Thus, the responding server must return all delegation assertions. But a cache server in the middle might drop some of the delegation assertions and it cannot check if they are complete. I came up with 2 possible options:
1) every rains server must respond with a shard or zone to a delegation query because then we can be sure that all delegation assertions are contained or non exist at all.
2) we make it possible to specify this information in a query.

**Comment by britram** [comment]
Multiple valid keys at once for a given keyphase is also a consistency error.
